name: WordPress Plugin Releaser
author: Gene Alyson Fortunado Torcende
description: Push a tagged version to the official repository

branding:
  icon: package
  color: red

inputs:
  slug:
    description: Custom plugin slug
    # default: ${GITHUB_REPOSITORY#*/}
  assets:
    description: Path to the assets
    # default: .wporg
  dryrun:
    description: Skip actual commit
    # default: false

outputs:
  svn-dir:
    description: Path to the SVN directory
    value: ${{ steps.action.outputs.svn-dir }}
  export-dir:
    description: Path to the export directory
    value: ${{ steps.action.outputs.export-dir }}
  plugin-zip:
    description: Path to the generated plugin zip
    value: ${{ steps.action.outputs.plugin-zip }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      id: action
      env:
        INPUT_SLUG: ${{ inputs.slug }}
        INPUT_DRYRUN: ${{ inputs.dryrun }}
        INPUT_ASSETS: ${{ inputs.assets }}
