name: WordPress Plugin Releaser

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.WPPR_REPOSITORY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Plugin
        run: | # modify this step as needed
          composer install --no-dev
          git add -f vendor

      - name: Release ${{ github.ref_name }}
        id: release
        uses: kermage/action-wp-plugin-releaser@latest
        with:
          slug: ${{ env.WPPR_SLUG }}
          assets: ${{ env.WPPR_ASSETS }}
          dryrun: ${{ env.WPPR_DRYRUN }}
        env:
          WPORG_USERNAME: ${{ secrets.WPORG_USERNAME }}
          WPORG_PASSWORD: ${{ secrets.WPORG_PASSWORD }}

      - name: Check outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.release.outputs.plugin-slug }}
          path: |
            ${{ steps.release.outputs.svn-dir }}
            ${{ steps.release.outputs.export-dir }}
            ${{ steps.release.outputs.plugin-zip }}
